apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: spr-cloud-stream-create-source
spec:
  title: "Lab: Create Source Application"
  description: "create the source app"
  workshop:
    image: jdk17-environment:*
    files:
      - http:
          url: "$(ingress_protocol)://$(workshop_namespace)-files.$(ingress_domain)/$(workshop_name).tar.gz"
      - path: .local/share/code-server
        image:
          url: ghcr.io/spring-academy/vscode-java-tools-$(platform_arch)-files:0.25.14
  request:
    parameters:
    - name: USER_DOMAIN
      value: "unknown.domain"
    - name: USER_EMAIL
      value: "somebody@unknown.domain"
  session:
    env:
      - name: WEBSERVER
        value: "$(ingress_protocol)://$(workshop_namespace)-files.$(ingress_domain)"
      - name: LESSON_LABEL
        value: create-source-app-start
    namespaces:
      budget: medium
    resources:
      memory: 2Gi
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      docker:
        enabled: true
        storage: 500Mi
        socket:
          # you must have this to enable docker ps, etc.
          enabled: true
        compose:
          services:
            kafka:
              image: apache/kafka:latest
              container_name: kafka
              hostname: kafka
              ports:
                - "9092:9092"
              environment:
                KAFKA_NODE_ID: 1
                KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT_DOCKER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
                KAFKA_LISTENERS: "PLAINTEXT_DOCKER://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092"
                KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT_DOCKER://kafka:29092,PLAINTEXT_HOST://localhost:9092"
                KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
                KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
                KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
                KAFKA_PROCESS_ROLES: "broker,controller"
                KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
                KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT_DOCKER"
                KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
                KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
    dashboards:
      - name: Editor
      - name: Terminal
    volumes:
    - name: workshop-setup-scripts
      secret:
        secretName: workshop-setup-scripts
        defaultMode: 0755
    volumeMounts:
    - name: workshop-setup-scripts
      mountPath: /opt/packages/workshop-setup-scripts/setup.d

  environment:
    objects:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: workshop-setup-scripts
      stringData:
        00-setup.sh: |
          #!/bin/bash
          # This is run at session creation
          set -e

          curl -L ${WEBSERVER}/exercises.tar.gz | tar -xvz -C ${HOME}

          # Stage the codebase
          # This script is used to checkout the codebase to the commit that corresponds to the lesson label from the commit message.

          # Note this file is meant to generalize the staging of the codebase via a provided LESSON_LABEL environment variable.
          # there are no explicit parameters for this script to maximize the decoupling of the lesson content from the staging script.

          # Env vars:
          # LESSON_LABEL: Label to search for in commits. Must be surrounded by <> in the commit message to match
          # LESSON_REPO_DIR: Location of the codebase repo, if not in ~/exercises

          get_sha_for_lesson_label() {
            git log --format=format:%H --grep "<$LESSON_LABEL>"
          }

          checkout_to_label() {
            lesson_sha=$(get_sha_for_lesson_label)
            if [[ -z "$lesson_sha" ]]; then
              echo "LESSON_LABEL '$LESSON_LABEL' has no matching commit for this workshop."
            else
              echo "Checking out from git. Label (Git commit containing text): <$LESSON_LABEL>, SHA: $lesson_sha"
              git checkout $lesson_sha
            fi
          }

          # Make sure we are in the root of the repo
          LESSON_REPO_DIR="${LESSON_REPO_DIR:-$HOME/exercises}"

          if [[ ! -d "$LESSON_REPO_DIR" ]]; then
            echo "No codebase at $LESSON_REPO_DIR. Exiting without error."
            exit 0
          fi

          if [[ -z "$LESSON_LABEL" ]]; then
            echo "No lesson label provided. Exiting without error."
            exit 0
          fi

          cd "$LESSON_REPO_DIR"
          checkout_to_label
    - apiVersion: v1
      kind: Service
      metadata:
        name: $(workshop_namespace)-files
        namespace: $(workshop_namespace)
      spec:
        type: ClusterIP
        ports:
        - port: 80
          protocol: TCP
          targetPort: 8080
        selector:
          deployment: files
    - apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: $(workshop_namespace)-files
        namespace: $(workshop_namespace)
      spec:
        tls:
        - hosts:
            - $(workshop_namespace)-files.$(ingress_domain)
          secretName: $(ingress_secret)
        rules:
        - host: $(workshop_namespace)-files.$(ingress_domain)
          http:
            paths:
            - backend:
                service:
                  name: $(workshop_namespace)-files
                  port:
                    number: 80
              pathType: Prefix
              path: /
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: $(workshop_namespace)-files
        namespace: $(workshop_namespace)
      spec:
        serviceAccountName: $(service_account)
        replicas: 1
        selector:
          matchLabels:
            deployment: files
        strategy:
          type: Recreate
        template:
          metadata:
            labels:
              deployment: files
          spec:
            containers:
            - name: files
              image: ${CONTAINER_REGISTRY}${CONTAINER_REPOSITORY}:${VERSION}